### ISSUE TITLE
How to install/requirements for this package?

### ISSUE THREAD

**Issue by JoostvDoorn** [apaszke/torch-nvtx#1]
I get the following error when trying to install this package. I have nvvp in my path, I am not familiar with the NVIDIA Tools Extension, and I cannot find it in my cuda directory. Any idea what I should do?

```
Scanning dependencies of target nvtx
[100%] Building C object CMakeFiles/nvtx.dir/nvtx.c.o
Linking CXX shared module libnvtx.so
/usr/bin/ld: cannot find -lnvToolsExt
collect2: error: ld returned 1 exit status
make[2]: *** [libnvtx.so] Error 1
make[1]: *** [CMakeFiles/nvtx.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by apaszke** [comment]
What's your platform? Could you try changing `/lib` in [this line](https://github.com/apaszke/torch-nvtx/blob/master/CMakeLists.txt#L14) to `/lib64`?

**Comment by JoostvDoorn** [comment]
Thanks that fixes it! I am on Linux/Ubuntu.
